# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fbc612738c7feb38f59884b56ddd21e397d16c657d6df9bb78afe2dc5652df15f24a797d810e7fcbbf3b4cdcac5ae62773e7ad8a0e2f5b4852194f4ca351a7e

test:
  secret_key_base: ff2396bf88aea74dfc85d6110d45b7ca6d2bfe4981a499a864b3f73ae609a5f77bb15d389bd88d3e81b03f810a5063affcdd59fe3e8904a24dc93a074e66b762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
